# Generated by Django 5.2.11 on 2026-02-14 17:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TarawihNight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "night_number",
                    models.PositiveSmallIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(29),
                        ],
                    ),
                ),
                ("start_surah", models.TextField(blank=True)),
                ("start_ayah", models.TextField(blank=True)),
                ("end_surah", models.TextField(blank=True)),
                ("end_ayah", models.TextField(blank=True)),
            ],
            options={"ordering": ["night_number"],},
        ),
        migrations.CreateModel(
            name="TarawihRakah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rakah_number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                ("start_surah", models.TextField(blank=True)),
                ("start_ayah", models.TextField(blank=True)),
                ("end_surah", models.TextField(blank=True)),
                ("end_ayah", models.TextField(blank=True)),
                (
                    "night",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rakahs",
                        to="tarawihapp.tarawihnight",
                    ),
                ),
            ],
            options={
                "ordering": ["night__night_number", "rakah_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("night", "rakah_number"), name="uniq_rakah_per_night"
                    )
                ],
            },
        ),
    ]
