# Generated by Django 5.2.11 on 2026-02-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarawihapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarawihrakah",
            name="full_recitation",
            field=models.TextField(blank=True),
        ),
    ]
